version: '3.7'

volumes:
  postgres_data:


services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./mediafiles:/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${postgres_name}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - TZ:'Asia/Kolkata'
      - PGTZ:'Asia/Kolkata'