version: '3.7'

volumes:
  postgres_data:


services:
  app:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 project.asgi:application"
    volumes:
      - .:/code
      - ./mediafiles:/mediafiles
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - db


  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${postgres_name}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - TZ:'Asia/Kolkata'
      - PGTZ:'Asia/Kolkata'