version: '3.7'

volumes:
  postgres_data:
  static_files:
  letsencrypt:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-production
    command: gunicorn -w 4 project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - ./mediafiles:/mediafiles
      - static_files:/staticfiles
      - /etc/letsencrypt:/etc/nginx/certs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.production-settings
    depends_on:
      - db


  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${postgres_name}
      - POSTGRES_USER=${postgres_user} 
      - POSTGRES_PASSWORD=${postgres_password}
      - TZ:'Asia/Kolkata'
      - PGTZ:'Asia/Kolkata'


  nginx:
      build:
        context: .
        dockerfile: ./nginx/Dockerfile-nginx
      volumes:
        - .:/code
        - ./mediafiles:/mediafiles
        - static_files:/staticfiles
        - ./nginx/certbot/logs/:/var/log/letsencrypt
        - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
        - /etc/letsencrypt:/etc/nginx/certs
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - app