# Generated by Django 3.0 on 2021-03-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rating_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='example2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Rating'),
        ),
    ]
