# Generated by Django 3.0 on 2021-03-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_storeitem_example2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='example2',
        ),
    ]
