# Generated by Django 3.0 on 2021-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210314_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordereditem',
            field=models.ManyToManyField(to='api.Cart'),
        ),
    ]
