# Generated by Django 3.0 on 2021-03-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210314_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordereddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='orderedtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordereditem', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('ordereddate', models.DateField(default=django.utils.timezone.now)),
                ('orderedtime', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ordereditem',
            field=models.ManyToManyField(to='api.ItemsData'),
        ),
        migrations.AlterField(
            model_name='previousorder',
            name='ordereditem',
            field=models.ManyToManyField(to='api.ItemsData'),
        ),
    ]
