# Generated by Django 3.0 on 2021-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210314_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
