# Generated by Django 3.0 on 2021-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210315_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='store_item',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/user_profile/'),
        ),
    ]
