# Generated by Django 3.0 on 2021-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210316_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Dry Fruits', 'Dry Fruits'), ('Exotics', 'Exotics'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
