# Generated by Django 3.0 on 2021-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210320_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='mediafiles/images/user_profile/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(upload_to='mediafiles/images/banner/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='mediafiles/images/recipe/'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(null=True, upload_to='mediafiles/images/store/'),
        ),
    ]
