# Generated by Django 3.0 on 2021-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210320_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Dried-Fruits', 'Dried-Fruits'), ('Exotics', 'Exotics'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
