# Generated by Django 3.0 on 2021-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210417_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='previousorder',
            name='ordered_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
