# Generated by Django 3.0 on 2021-04-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210424_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home-products/')),
                ('category', models.CharField(choices=[('Custom1', 'Custom1'), ('Custom2', 'Custom2')], max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Dried-Fruits', 'Dried-Fruits'), ('Exotics', 'Exotics'), ('Other', 'Other'), ('Banner1', 'Banner1')], max_length=50, null=True),
        ),
    ]
