# Generated by Django 3.0 on 2021-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210427_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproducts',
            name='category',
            field=models.CharField(choices=[('Custom1', 'Custom1'), ('Custom2', 'Custom2'), ('Custom3', 'Custom3'), ('Custom4', 'Custom4')], max_length=255, null=True),
        ),
    ]
