# Generated by Django 3.0 on 2021-04-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210427_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='previous_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Dried-Fruits', 'Dried-Fruits'), ('Exotics', 'Exotics'), ('Other', 'Other'), ('Banner1', 'Banner1'), ('Banner2', 'Banner2'), ('Custom1', 'Custom1'), ('Custom2', 'Custom2'), ('Custom3', 'Custom3'), ('Custom4', 'Custom4')], max_length=50, null=True),
        ),
    ]
