# Generated by Django 3.0 on 2021-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_items_price',
            field=models.IntegerField(default=0),
        ),
    ]
