# Generated by Django 3.0 on 2021-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_activeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='order_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
