# Generated by Django 3.0 on 2021-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210501_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorder',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
