# Generated by Django 3.0 on 2021-05-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210501_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeorder',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Out for delivery', 'Out for delivery'), ('Order Delivered', 'Order Delivered'), ('Order Cancelled', 'Order Cancelled')], default='Order Placed', max_length=255),
        ),
    ]
