# Generated by Django 3.0 on 2021-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210513_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
