# Generated by Django 3.0 on 2021-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210517_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
