# Generated by Django 3.0 on 2021-05-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210527_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='price',
        ),
        migrations.CreateModel(
            name='VariableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('previous_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StoreItem')),
            ],
        ),
    ]
