# Generated by Django 3.0 on 2021-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210527_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableitem',
            name='item',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
