# Generated by Django 3.0 on 2021-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210527_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
