# Generated by Django 3.0 on 2021-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_cart_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordereditem',
        ),
        migrations.RemoveField(
            model_name='previousorder',
            name='ordereditem',
        ),
        migrations.AddField(
            model_name='order',
            name='ordereditems',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='ordereditems',
            field=models.TextField(null=True),
        ),
    ]
