# Generated by Django 3.0 on 2021-06-06 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210603_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousorder',
            name='delivery_and_package_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='delivery_and_package_review',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotificationstoken',
            name='token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
