# Generated by Django 3.0 on 2021-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210606_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='payment_mode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
