# Generated by Django 3.0 on 2021-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210614_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/RecipeIngredients/'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='show_weight_in_recipe',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
