# Generated by Django 3.0 on 2021-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210614_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproducts',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
