# Generated by Django 3.0 on 2021-10-30 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20210727_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(max_length=255, null=True)),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('starttime', models.TimeField(default=django.utils.timezone.now)),
                ('subscription_status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=255)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ordereditems', models.TextField(null=True)),
                ('cart_total', models.IntegerField(null=True)),
                ('coupon', models.IntegerField(default=0)),
                ('delivery_charges', models.IntegerField(default=25)),
                ('taxes', models.IntegerField(default=30)),
                ('total_subscription_price', models.IntegerField(null=True)),
                ('delivery_address', models.CharField(max_length=255, null=True)),
                ('delivery_locality', models.CharField(max_length=255, null=True)),
                ('delivery_city', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_authenticity', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('item_weight', models.CharField(max_length=255, null=True)),
                ('item_price', models.IntegerField()),
                ('item_count', models.IntegerField()),
                ('id_of_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordereditem', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=255, null=True)),
                ('ordereddate', models.DateField(default=django.utils.timezone.now)),
                ('orderedtime', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
