# Generated by Django 3.0 on 2021-10-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_subscription_subscriptioncart_subscriptionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
