# Generated by Django 3.0 on 2021-11-07 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_subscription_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubscriptionRecipeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255, null=True)),
                ('recipe_price', models.IntegerField()),
                ('category', models.CharField(max_length=255, null=True)),
                ('id_of_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSubscriptionCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=255, null=True)),
                ('ordereddate', models.DateField(default=django.utils.timezone.now)),
                ('orderedtime', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
