# Generated by Django 3.0 on 2021-11-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20211107_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
