# Generated by Django 3.0 on 2021-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_subscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Dried-Fruits', 'Dried-Fruits'), ('Exotics', 'Exotics'), ('Banner1', 'Banner1'), ('Banner2', 'Banner2'), ('Immuntiy-Booster', 'Immuntiy-Booster'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
